echo ""
echo "# Firing up jupyter notebook"
echo "#"
echo "#"
echo "###########################################################"
echo "#"
echo "#"
echo "#"
echo "# Open notebook at http://localhost:8888/?token=datascience"
echo "#"
echo "#"
echo "#"
echo "###########################################################"
echo "#"
echo "#"
jupyter notebook --ip 0.0.0.0 --no-browser --allow-root --NotebookApp.token='datascience'
